CHANGELOG.md
deploy/role/superset-cluster-role.yaml

The operator is now allowed to watch for commands. The missing rule was not detected by the integration tests because the Init command is applied so early that the test case was able to "get" it and did not need to "watch" for it.

Add missing rule to the cluster role

---

CHANGELOG.md
deploy/crd/supersetcluster.crd.yaml
deploy/helm/superset-operator/crds/crds.yaml
deploy/manifests/crds.yaml
rust/crd/src/lib.rs
rust/operator-binary/src/superset_controller.rs

Fixes https://github.com/stackabletech/superset-operator/issues/264
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

Add temporary attribute to support using ClusterIP instead of NodePort service type

---

CHANGELOG.md
rust/crd/src/lib.rs
rust/operator-binary/src/superset_controller.rs

Fixes https://github.com/stackabletech/superset-operator/issues/248
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: Rename Service port name from `superset` to `http`

---

docs/modules/superset/pages/getting_started/installation.adoc
docs/modules/superset/pages/index.adoc

Part of https://github.com/stackabletech/stackable-cockpit/pull/101

docs: Update references

---

deploy/helm/superset-operator/templates/roles.yaml
docs/modules/superset/pages/index.adoc

Cleanup, we forgot to remove those things in https://github.com/stackabletech/superset-operator/pull/396
Basically the same as https://github.com/stackabletech/airflow-operator/pull/331
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Removed SupersetDB references in docs and RBAC config

---

Cargo.lock
Cargo.toml
deploy/helm/superset-operator/configs/properties.yaml
deploy/helm/superset-operator/crds/crds.yaml
rust/crd/src/lib.rs
rust/operator-binary/src/druid_connection_controller.rs
rust/operator-binary/src/superset_controller.rs

Part of https://github.com/stackabletech/operator-rs/issues/649

refactor: Use operator-rs Duration

---

CHANGELOG.md
Cargo.toml
deploy/helm/superset-operator/crds/crds.yaml
docs/modules/superset/pages/usage-guide/operations/graceful-shutdown.adoc
rust/crd/src/lib.rs
rust/operator-binary/src/operations/graceful_shutdown.rs
rust/operator-binary/src/operations/mod.rs
rust/operator-binary/src/product_logging.rs
rust/operator-binary/src/superset_controller.rs
tests/templates/kuttl/smoke/30-assert.yaml

Part of https://github.com/stackabletech/issues/issues/357
- grace period currently 2min
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Support graceful shutdown

---

docs/modules/superset/examples/getting_started/getting_started.sh
docs/modules/superset/examples/getting_started/getting_started.sh.j2
docs/modules/superset/examples/getting_started/superset-load-examples-job.yaml.j2
docs/modules/superset/pages/getting_started/installation.adoc
docs/templating_vars.yaml

The listener-operator is now one of the fundamental operators, along with the commons- and secret-operators, and should be mentioned accordingly everywhere.
Add changes from https://github.com/stackabletech/superset-operator/commit/c50bcff2521f67994302684005a605adc71ee1dd#diff-2b236650ca0d74d6bb0e5931c2dd8a65e59c63637e4e3d9d89ea62b915e46e58 to the template file.
```[tasklist]
```
```[tasklist]
```

docs: Add listener-operator where missing

---

docs/modules/superset/pages/getting_started/first_steps.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Fix missing clusterConfig reference

---

CHANGELOG.md
deploy/helm/superset-operator/crds/crds.yaml
rust/crd/src/affinity.rs
rust/crd/src/lib.rs

Part of https://github.com/stackabletech/issues/issues/469
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: Fixed various issues in the CRD structure

---

rust/crd/src/authentication.rs

- Reword confusing error message.
- Apply [code-style rules][1] to the remaining error variants in that enum.
[1]: https://docs.stackable.tech/home/nightly/contributor/code-style-guide#_error_messages

chore: improve error message

---

CHANGELOG.md
rust/operator-binary/src/superset_controller.rs

Fixes https://github.com/stackabletech/internal-issues/issues/85
First commit is just making script better readable in k8s.
Actual fix is wrapping the command leaking the credentials with `set +x` and `set -x`.
Ideally we want a test for this, but I don't know how to test this (other than grepping for the password in the logs)
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: Don't print Superset admin credentials during startup

---

CHANGELOG.md
rust/operator-binary/src/superset_controller.rs

When DB initialization fails for **some** reason `prepare_signal_handlers` get's called and errors. This is mostly a clean up change, as the Pod is crashlooping anyway :sweat_smile: It's just deflecting from the root cause.
```
k logs superset-node-default-0
Defaulted container "superset" out of: superset, metrics
+ mkdir --parents /stackable/app/pythonpath
+ cp /stackable/config/log_config.py /stackable/config/superset_config.py /stackable/app/pythonpath
+ cp /stackable/log_config/log_config.py /stackable/app/pythonpath
+ superset db upgrade
'FLASK_ENV' is deprecated and will not be used in Flask 2.3. Use 'FLASK_DEBUG' instead.
2024-04-19 17:33:25,373:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
2024-04-19 …
```

fix: Entrypoint error when DB initialization fails

---

tests/templates/kuttl/smoke/31-assert.yaml

Kuttl hard codes `sh -c`, instead of allowing alternative shells to be used.
For now, we need to drop the `-o pipefail` option.
See: https://github.com/kudobuilder/kuttl/issues/557
> [!NOTE]
> For zsh users, `sh` appears to just alias zsh, so locally `set -euo pipfail` worked fine.

test(kuttl): Remove the -o pipefail bash option

---

CHANGELOG.md
rust/operator-binary/src/druid_connection_controller.rs
rust/operator-binary/src/main.rs
rust/operator-binary/src/superset_controller.rs

Part of: https://github.com/stackabletech/issues/issues/211
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: invalid objects don't stop the reconciliation

---

rust/operator-binary/src/main.rs

Something went wrong here: https://github.com/stackabletech/superset-operator/pull/551
This fixes it.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

update usage of DeserializsedGuard refs

---

docs/modules/superset/examples/getting_started/getting_started.sh
docs/modules/superset/examples/getting_started/getting_started.sh.j2

Part of https://github.com/stackabletech/issues/issues/611.
Depends on https://github.com/stackabletech/superset-operator/pull/565.

chore(getting_started): Replace templating instructions with make

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/crd/src/authentication.rs
rust/operator-binary/Cargo.toml
rust/operator-binary/src/config.rs
rust/operator-binary/src/superset_controller.rs
tests/templates/kuttl/oidc/install-keycloak.yaml.j2

Part of https://github.com/stackabletech/operator-rs/pull/910
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: Construction of OIDC endpoint when rootPath has a trailing slash

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
Makefile
crate-hashes.json
docs/modules/superset/examples/getting_started/getting_started.sh
docs/modules/superset/examples/getting_started/getting_started.sh.j2
rust/crd/src/authentication.rs
rust/operator-binary/Cargo.toml
rust/operator-binary/src/config.rs
rust/operator-binary/src/superset_controller.rs
tests/templates/kuttl/druid-connection/20-assert.yaml
tests/templates/kuttl/druid-connection/20-install-superset.yaml.j2
tests/templates/kuttl/druid-connection/30-assert.yaml
tests/templates/kuttl/druid-connection/30-install-druid-connection.yaml
tests/templates/kuttl/oidc/install-keycloak.yaml.j2

Add the following PRs to the release 24.11:
* #565 
* #566 
* #568 
* #569

Update release branch

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
deploy/helm/superset-operator/crds/crds.yaml
deploy/helm/superset-operator/values.yaml
docs/modules/superset/examples/getting_started/superset-load-examples-job.yaml
docs/modules/superset/examples/getting_started/superset-load-examples-job.yaml.j2
docs/modules/superset/pages/reference/environment-variables.adoc
tests/templates/kuttl/ldap/60-install-test-container.yaml
tests/templates/kuttl/logging/30-install-test-container.yaml
tests/templates/kuttl/oidc/50-install-test-container.yaml.j2
tests/templates/kuttl/smoke/40-install-test-container.yaml

Openshift tests:
```
--- PASS: kuttl (666.75s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/resources_superset-latest-4.0.2_openshift-true (145.03s)
--- PASS: kuttl/harness/ldap_superset-4.0.2_ldap-authentication-no-tls_openshift-true (145.47s)
--- PASS: kuttl/harness/logging_superset-4.0.2_openshift-true (104.47s)
--- PASS: kuttl/harness/ldap_superset-4.0.2_ldap-authentication-insecure-tls_openshift-true (121.68s)
--- PASS: kuttl/harness/oidc_superset-4.0.2_openshift-true (148.64s)
--- PASS: kuttl/harness/cluster-operation_superset-latest-4.0.2_openshift-true (264.06s)
--- PASS: kuttl/harness/smoke_superset-4.0.2_openshift-true (142.99s)
--- PASS: kuttl/harness/druid-connection_superset-4.0.2_openshift-true (110.94s)
--- PASS: …
```

chore: add oci references, merge templating changes

---

tests/templates/kuttl/opa/51-install-test-container.yaml.j2

Part of https://github.com/stackabletech/infrastructure/issues/142
Repository references were already updated for this repo with changelog entry already present, new old docker.stackable.tech reference was added after, this PR fixes that.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: update to oci references

---

docs/modules/superset/examples/getting_started/getting_started.sh
docs/modules/superset/examples/getting_started/getting_started.sh.j2
docs/modules/superset/pages/getting_started/installation.adoc
docs/templating_vars.yaml
examples/superset-with-ldap.yaml

Part of https://github.com/stackabletech/infrastructure/issues/142
Updating the helm install commands in Getting started sections of the operators was missed during Harbor migration of the docs.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Update helm install commands

---

CHANGELOG.md
tests/templates/kuttl/logging/10-install-superset-vector-aggregator.yaml

Part of https://github.com/stackabletech/docker-images/issues/1085.
- Bump to Vector 0.46.1 in tests

test: Bump vector to 0.46.1

---

CHANGELOG.md
rust/operator-binary/src/druid_connection_controller.rs
rust/operator-binary/src/superset_controller.rs

Part of https://github.com/stackabletech/issues/issues/651
Remove hardcoded uid and gid, they'll default to the ones from the docker images now.
For 25.7 that means they might change from 1000/0
See https://github.com/stackabletech/docker-images/pull/916 for details

chore: Remove hardcoded uid and gid

---

tests/templates/kuttl/opa/30-assert.yaml

Latest weekly tests fail while waiting for the OPA Daemonsets to become ready.
For example: https://testing.stackable.tech/job/superset-operator-it-weekly/57/artifact/target/test-output.log/*view*/

tests: increase OPA assert timeouts

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/operator-binary/src/main.rs
rust/operator-binary/src/superset_controller.rs

Superset 4.0 and 4.1 both failed to start quick enough on a customer setup on Rhoencloud and crashlooped.
Fixed it via podOverrides, adding the probe to the operator here

fix: Add startupProbe to prevent Superset startup problems

---

CHANGELOG.md
docs/modules/superset/examples/getting_started/superset-load-examples-job.yaml
docs/modules/superset/examples/getting_started/superset-load-examples-job.yaml.j2
docs/modules/superset/examples/getting_started/superset.yaml
docs/modules/superset/pages/usage-guide/security.adoc
docs/modules/superset/partials/supported-versions.adoc
examples/superset-with-ldap.yaml
rust/operator-binary/src/crd/affinity.rs
tests/test-definition.yaml

Part of https://github.com/stackabletech/docker-images/issues/1274
```
--- PASS: kuttl (884.85s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/external-access_superset-4.1.4_openshift-false (131.80s)
--- PASS: kuttl/harness/smoke_superset-4.1.4_openshift-false (202.35s)
--- PASS: kuttl/harness/ldap_superset-4.1.4_ldap-authentication-server-verification-tls_openshift-false (149.11s)
--- PASS: kuttl/harness/resources_superset-latest-4.1.4_openshift-false (146.67s)
--- PASS: kuttl/harness/oidc_superset-4.1.4_openshift-false (228.68s)
--- PASS: kuttl/harness/logging_superset-4.1.4_openshift-false (192.70s)
--- PASS: kuttl/harness/druid-connection_superset-4.1.4_openshift-false (83.76s)
--- PASS: kuttl/harness/cluster-operation_superset-latest-4.1.4_openshift-false (134.04s)
--- …
```

chore: Superset - bump patch versions for 25.11
