stackabletech/superset-operator

CHANGELOG.md
Cargo.lock
deploy/helm/superset-operator/Chart.yaml
deploy/manifests/configmap.yaml
deploy/manifests/deployment.yaml
deploy/manifests/serviceaccount.yaml
rust/crd/Cargo.toml
rust/operator-binary/Cargo.toml

Release 0.2.0

---

Cargo.lock
rust/crd/Cargo.toml

Fixes #66
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

Drop duplicate dependency

---

CHANGELOG.md
Cargo.lock
rust/crd/Cargo.toml
rust/operator-binary/src/init_controller.rs
rust/operator-binary/src/main.rs
rust/operator-binary/src/superset_controller.rs

- README update
- Dependency updates
- Remove unused dependencies
- Rustdoc fixes
- Graceful shutdown
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

Various changes

---

CHANGELOG.md
deploy/helm/superset-operator/crds/crds.yaml
rust/crd/src/lib.rs

cherry picked from commit 014f081349823f40a8da1ae5dd075d4a18907495
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

Add missing crd defaults to 23.4

---

CHANGELOG.md
Cargo.lock
deploy/helm/superset-operator/crds/crds.yaml
docs/modules/superset/examples/getting_started/superset.yaml
docs/modules/superset/examples/getting_started/superset.yaml.j2
docs/modules/superset/pages/usage-guide/security.adoc
examples/superset-with-ldap.yaml
rust/crd/Cargo.toml
rust/crd/src/affinity.rs
rust/crd/src/supersetdb.rs
rust/operator-binary/Cargo.toml
rust/operator-binary/src/druid_connection_controller.rs
rust/operator-binary/src/main.rs
rust/operator-binary/src/superset_controller.rs
rust/operator-binary/src/superset_db_controller.rs
tests/templates/kuttl/cluster-operation/02-install-superset.yaml.j2
tests/templates/kuttl/cluster-operation/03-install-superset-pause.yaml.j2
tests/templates/kuttl/cluster-operation/04-install-superset-stop.yaml.j2
tests/templates/kuttl/cluster-operation/05-install-superset-restart.yaml.j2
tests/templates/kuttl/druid-connection/02-install-superset.yaml.j2
tests/templates/kuttl/ldap/5-install-superset.yaml.j2
tests/templates/kuttl/logging/02-install-superset.yaml.j2
tests/templates/kuttl/resources/02-install-superset.yaml.j2
tests/templates/kuttl/smoke/30-install-superset.yaml.j2
tests/test-definition.yaml

Part of https://github.com/stackabletech/issues/issues/404
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat: Default stackableVersion to operator version

---

CHANGELOG.md
tests/kuttl-test.yaml.jinja2
tests/templates/kuttl/logging/01-install-superset-vector-aggregator.yaml
tests/templates/kuttl/logging/superset-vector-aggregator-values.yaml.j2
tests/templates/kuttl/logging/test_log_aggregation.py

Upgrade vector
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Upgrade vector

---

Cargo.lock
Cargo.toml
deploy/helm/superset-operator/crds/crds.yaml
rust/crd/Cargo.toml
rust/operator-binary/Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Switch to workspace dependencies

---

docs/modules/superset/pages/getting_started/first_steps.adoc
docs/modules/superset/pages/index.adoc
docs/modules/superset/pages/required-external-components.adoc
docs/modules/superset/partials/nav.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: added required external components

---

deploy/helm/superset-operator/crds/crds.yaml
docs/modules/superset/pages/usage-guide/listenerclass.adoc
docs/modules/superset/partials/nav.adoc
rust/crd/src/lib.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

ListenerClass docs

---

Cargo.lock
Cargo.toml
rust/crd/Cargo.toml
rust/crd/src/lib.rs
rust/operator-binary/Cargo.toml
rust/operator-binary/src/superset_controller.rs

Part of https://github.com/stackabletech/product-config/issues/95

refactor: Use updated product-config

---

docs/modules/superset/examples/getting_started/superset-load-examples-job.yaml
tests/templates/kuttl/cluster-operation/02-install-superset.yaml.j2
tests/templates/kuttl/cluster-operation/03-install-superset-pause.yaml.j2
tests/templates/kuttl/cluster-operation/04-install-superset-stop.yaml.j2
tests/templates/kuttl/cluster-operation/05-install-superset-restart.yaml.j2
tests/templates/kuttl/druid-connection/02-install-superset.yaml.j2
tests/templates/kuttl/resources/02-install-superset.yaml.j2
tests/templates/kuttl/smoke/30-install-superset.yaml.j2

Set examples to use postgres db and remove dead test fields.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Getting-started scripts - override sqlite3 for examples database

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deploy/helm/superset-operator/crds/crds.yaml
rust/crd/src/authentication.rs
rust/crd/src/druidconnection.rs
rust/crd/src/lib.rs
rust/operator-binary/src/main.rs

Better CRD docs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat: Better CRD docs

---

Cargo.toml
rust/operator-binary/src/product_logging.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: clippy lint

---

docs/modules/superset/pages/usage-guide/logging.adoc
tests/templates/kuttl/logging/02-install-superset.yaml.j2

fixes https://github.com/stackabletech/superset-operator/issues/441
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Remove left over databaseInitialization references

---

Cargo.lock
Cargo.toml
deploy/helm/superset-operator/crds/crds.yaml
rust/crd/src/affinity.rs
rust/crd/src/authentication.rs
rust/crd/src/lib.rs
rust/operator-binary/src/config.rs
rust/operator-binary/src/superset_controller.rs
rust/operator-binary/src/util.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: bump operator rs 0.61

---

CHANGELOG.md
deploy/helm/superset-operator/templates/_helpers.tpl
deploy/helm/superset-operator/templates/deployment.yaml
deploy/helm/superset-operator/templates/roles.yaml
deploy/helm/superset-operator/values.yaml

Part of: https://github.com/stackabletech/issues/issues/501

feat(helm): support labels in values.yaml

---

docs/modules/superset/pages/usage-guide/connecting-druid.adoc

fixes #445 
```[tasklist]
```
```[tasklist]
```

docs: document network access requirement for DruidConnection feature

---

docs/modules/superset/pages/usage-guide/security.adoc

introduced in https://github.com/stackabletech/superset-operator/pull/423 and broke my antora build!
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Fix callout list

---

deploy/helm/superset-operator/values.yaml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add Stackable vendor label to default values.yaml

---

CHANGELOG.md
docs/modules/superset/examples/getting_started/superset-load-examples-job.yaml
docs/modules/superset/examples/getting_started/superset-load-examples-job.yaml.j2
docs/modules/superset/examples/getting_started/superset.yaml
docs/modules/superset/pages/usage-guide/security.adoc
docs/modules/superset/partials/supported-versions.adoc
examples/superset-with-ldap.yaml
rust/crd/src/affinity.rs
tests/templates/kuttl/logging/01-install-superset-vector-aggregator.yaml
tests/test-definition.yaml

- Add superset versions 2.1.3, 3.0.3, 3.1.0
- Removed version 2.1.0
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Support versions 2.1.3, 3.0.3, 3.1.0

---

rust/crd/src/authentication.rs

Update unit tests with new error messages.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(test): update error messages

---

docs/modules/superset/pages/index.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: update supported versions text and other minor changes

---

docs/modules/superset/pages/usage-guide/logging.adoc
docs/modules/superset/pages/usage-guide/monitoring.adoc
docs/modules/superset/pages/usage-guide/security.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: fix links

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
tests/templates/kuttl/logging/21-copy-prepared-logs.yaml
tests/templates/kuttl/logging/prepared-logs.py.json
tests/templates/kuttl/logging/superset-vector-aggregator-values.yaml.j2

Add prepared logs to the logging test containing invalid log events
Tests stackabletech/operator-rs#802
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add prepared logs to the logging test

---

tests/templates/kuttl/logging/10-install-superset-vector-aggregator.yaml

Use Vector Helm chart version 0.34.0 (Vector 0.39.0) in the logging test
https://github.com/vectordotdev/helm-charts/blob/vector-0.34.0/CHANGELOG.md#vector-0340---2024-06-17
Implements stackabletech/docker-images#561
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Use Vector Helm chart version 0.34.0 in the logging test

---

docs/modules/superset/examples/getting_started/getting_started.sh
docs/modules/superset/examples/getting_started/getting_started.sh.j2
docs/modules/superset/examples/getting_started/install_output.txt
docs/modules/superset/examples/getting_started/install_output.txt.j2
docs/modules/superset/pages/getting_started/installation.adoc

docs(getting-started): update stackablectl op install output

---

tests/templates/kuttl/logging/10-install-superset-vector-aggregator.yaml

Part of https://github.com/stackabletech/issues/issues/626
```[tasklist]
```

chore: Bump Vector to 0.40.0

---

deploy/helm/superset-operator/templates/roles.yaml

See: https://github.com/stackabletech/issues/issues/624
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(helm): use same scc as olm

---

tests/templates/kuttl/logging/10-install-superset-vector-aggregator.yaml

Upgrade the Vector aggregator in the logging tests
The Helm chart version 0.36.1 deploys Vector 0.41.1.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Upgrade the Vector aggregator in the logging tests

---

docs/modules/superset/pages/index.adoc
docs/modules/superset/pages/required-external-components.adoc
docs/modules/superset/pages/usage-guide/configuration-environment-overrides.adoc
docs/modules/superset/pages/usage-guide/connecting-druid.adoc
docs/modules/superset/pages/usage-guide/index.adoc
docs/modules/superset/pages/usage-guide/listenerclass.adoc
docs/modules/superset/pages/usage-guide/logging.adoc
docs/modules/superset/pages/usage-guide/monitoring.adoc
docs/modules/superset/pages/usage-guide/security.adoc
docs/modules/superset/pages/usage-guide/storage-resource-configuration.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add descriptions

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deploy/helm/superset-operator/crds/crds.yaml
rust/crd/src/authentication.rs
rust/operator-binary/src/controller_commons.rs
rust/operator-binary/src/superset_controller.rs

part of: https://github.com/stackabletech/issues/issues/640
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: bump op-rs

---

docs/modules/superset/examples/getting_started/getting_started.sh
docs/modules/superset/examples/getting_started/install_output.txt
docs/modules/superset/examples/getting_started/superset-load-examples-job.yaml

Part of https://github.com/stackabletech/issues/issues/647.

docs: Update release in getting_started

---

CHANGELOG.md
Cargo.lock
Cargo.nix
rust/operator-binary/src/superset_controller.rs
tests/templates/kuttl/smoke/30-assert.yaml
tests/templates/kuttl/smoke/32-assert.yaml

Part of <https://github.com/stackabletech/issues/issues/527>
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat: run containerdebug in the background

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
deploy/helm/superset-operator/templates/roles.yaml
rust/operator-binary/Cargo.toml
rust/operator-binary/src/druid_connection_controller.rs
rust/operator-binary/src/main.rs
rust/operator-binary/src/superset_controller.rs

Part of https://github.com/stackabletech/operator-rs/issues/942
```[tasklist]
```

chore: Update to operator-rs 0.84.0

---

tests/templates/kuttl/cluster-operation/20-install-superset.yaml.j2
tests/templates/kuttl/cluster-operation/30-install-superset-pause.yaml.j2
tests/templates/kuttl/cluster-operation/40-install-superset-stop.yaml.j2
tests/templates/kuttl/cluster-operation/50-install-superset-restart.yaml.j2
tests/templates/kuttl/druid-connection/20-install-superset.yaml.j2
tests/templates/kuttl/ldap/50-install-superset.yaml.j2
tests/templates/kuttl/logging/21-install-superset.yaml.j2
tests/templates/kuttl/oidc/install-superset.yaml.j2
tests/templates/kuttl/resources/20-install-superset.yaml.j2
tests/templates/kuttl/smoke/30-install-superset.yaml.j2
tests/test-definition.yaml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: tests with custom images

---

docs/modules/superset/examples/getting_started/getting_started.sh
docs/modules/superset/examples/getting_started/getting_started.sh.j2

Part of <https://github.com/stackabletech/issues/issues/697>
This PR bumps the following charts:
- `postgresql` to 16.5.0
```shell
kind delete cluster && kind create cluster
./getting_started.sh stackablectl
kind delete cluster && kind create cluster
./getting_started.sh helm
```

chore(docs): Update getting-started script pre-25.3.0

---

Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json

```
--- PASS: kuttl (784.99s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/ldap_superset-4.1.1_ldap-authentication-insecure-tls_openshift-false (180.70s)
--- PASS: kuttl/harness/logging_superset-4.0.2_openshift-false (188.37s)
--- PASS: kuttl/harness/opa_superset-4.1.1_opa-latest-1.0.1_openshift-false (255.01s)
--- PASS: kuttl/harness/resources_superset-latest-4.1.1_openshift-false (83.75s)
--- PASS: kuttl/harness/oidc_superset-4.1.1_openshift-false (113.48s)
--- PASS: kuttl/harness/cluster-operation_superset-latest-4.1.1_openshift-false (88.56s)
--- PASS: kuttl/harness/oidc_superset-4.0.2_openshift-false (102.81s)
--- PASS: kuttl/harness/ldap_superset-4.0.2_ldap-authentication-no-tls_openshift-false (101.67s)
--- PASS: …
```

chore: Bump stackable-operator to 0.87.5

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/operator-binary/Cargo.toml
rust/operator-binary/src/main.rs

Part of https://github.com/stackabletech/issues/issues/639.
> [!WARNING]
> This PR adds a bunch of lines now that will be collapsed into a single line later (with https://github.com/stackabletech/operator-rs/pull/1001). This has been decided so that we unblock others working on operator-rs changes.
- Replace `print_startup_string` with structured event
- Use `stackable_telemetry::Tracing`
- BREAKING: File log directory is now set by `ROLLING_LOGS`.
- In this PR, if the operator is deployed via Helm, rolling file logs will be disabled because the chart doesn't yet support additional args/env vars. A follow up PR will cover this.
- Please make sure all …

feat!: Use stackable-telemetry

---

rust/operator-binary/src/crd/authentication.rs

Add link to clarify hardcoded preferred_username

Add flask preferred username hint

---

docs/modules/superset/examples/getting_started/superset-load-examples-job.yaml
docs/modules/superset/examples/getting_started/superset-load-examples-job.yaml.j2
docs/modules/superset/examples/getting_started/superset.yaml
docs/modules/superset/pages/usage-guide/security.adoc
docs/modules/superset/partials/supported-versions.adoc
examples/superset-with-ldap.yaml
rust/operator-binary/src/crd/affinity.rs
tests/test-definition.yaml

Part of https://github.com/stackabletech/docker-images/issues/1081.
- Add Superset 4.1.2
- Deprecate Superset 4.1.1
- Update tests
- Update getting-started and examples

chore: Add Superset 4.1.2

---

CHANGELOG.md
tests/templates/kuttl/opa/30-install-opa.yaml.j2
tests/test-definition.yaml

Part of https://github.com/stackabletech/docker-images/issues/1084.

test: Bump OPA to 1.4.2

---

tests/templates/kuttl/logging/10-install-superset-vector-aggregator.yaml

Part of: https://github.com/stackabletech/docker-images/issues/1146

chore: bump vector chart to 0.43.0

---

tests/templates/kuttl/druid-connection/20-assert.yaml

test: remove old service account assert

---

Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/operator-binary/src/authorization/opa.rs
rust/operator-binary/src/crd/mod.rs
rust/operator-binary/src/druid_connection_controller.rs
rust/operator-binary/src/main.rs
rust/operator-binary/src/service.rs
rust/operator-binary/src/superset_controller.rs

Part of https://github.com/stackabletech/issues/issues/762

chore: Update to stackable-operator 0.95.0

---

tests/test-definition.yaml

Part of https://github.com/stackabletech/docker-images/issues/1238
```
--- PASS: kuttl (805.73s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/opa_superset-4.0.2_opa-latest-1.8.0_openshift-false (424.42s)
--- PASS: kuttl/harness/opa_superset-4.1.2_opa-latest-1.8.0_openshift-false (432.03s)
--- PASS: kuttl/harness/opa_superset-4.1.1_opa-latest-1.8.0_openshift-false (381.29s)
PASS
```

chore: Bump opa version for 25.11.0
